### ISSUE TITLE
svg files

### ISSUE THREAD

**Issue by mikeblackstock** [os-js/osjs-preview-application#6]
Could svg files be displayed? 

I had a look in https://github.com/os-js/osjs-gui/blob/master/src/components/Image.js
and it's not obvious to me why svg file display is broken.

Thx,
M.

**Comment by andersevenrud** [comment]
I believe this is because the osjs-server does not send the `Content-Type` header on readdir outside downloads. Feel free to open an issue in that repo and I'll fix it ASAP :)
